services:
  mssql-benchmarks-database:
    container_name: 'mssql-benchmarks-database'
    image: 'mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04'
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ABCdef123|+.
      - MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS
    restart: always